name          'ivanlei-rvm'
version       '1.0.0'
summary       'Puppet module for rvm'
description   'Puppet module for rvm'
source        'https://github.com/ivanlei/puppet-rvm.git'
project_page  'https://github.com/ivanlei/puppet-rvm'
license       'Modified BSD License'
